---

# role comes from https://github.com/k3s-io/k3s-ansible
- hosts: master
  become: yes
  gather_facts: yes
  roles:
    # in case any changes in /etc/rancher/k3s/config.yaml
    - role: k3s-initial-config
    - role: k3s/master
    - role: k3s-get-kubeconfig-local
    - role: flannel-cni
    - role: k3s-oidc

# this role depends on 'token' value retrieved above
# role comes from https://github.com/k3s-io/k3s-ansible
- hosts: node
  become: yes
  gather_facts: true
  roles:
    - role: k3s/node
