apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: golang-hello-world-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: golang-hello-world-web
  minReplicas: 1
  maxReplicas: 2
  metrics:
  # only valid for autoscaling/v2beta1
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 40 # deprecated at v2beta2
  # valid at v2beta2 and v2
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 40
