---

- name: check kubectl
  become: yes
  command: kubectl get nodes
  register: getnodes
- debug: msg="{{getnodes.stdout_lines}}"

- name: creates directories
  file:
    path: "{{item}}"
    state: directory
  loop: ['primary-ingress','secondary-ingress']

- name: render templates for primary-ingress
  template:
    src: "{{item}}"
    dest: primary-ingress/.
  with_fileglob: "../templates/primary-ingress/*.*"

- name: render templates for nginx secondary ingress
  template:
    src: "{{item}}"
    dest: secondary-ingress/.
  with_fileglob: "../templates/secondary-ingress/*.*"

- name: kubectl apply for primary
  become: yes
  shell:
    cmd: "kubectl apply -f primary-ingress/{{ item | basename }}"
  with_fileglob: "../templates/primary-ingress/*.*"
  register: k8sapply_results
- debug: msg="{{k8sapply_results}}"

- name: kubectl apply for secondary
  become: yes
  shell:
    cmd: "kubectl apply -f primary-ingress/{{ item | basename }}"
  with_fileglob: "../templates/primary-ingress/*.*"
  register: k8sapply_results
  when: do_second_ingress
- debug: msg="{{k8sapply_results}}"
